//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: messages.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `MessagesClient`, then call methods of this protocol to make API calls.
internal protocol MessagesClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: MessagesClientInterceptorFactoryProtocol? { get }

  func getMessages(
    _ request: GetMessagesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetMessagesRequest, GetMessagesResponse>
}

extension MessagesClientProtocol {
  internal var serviceName: String {
    return "Messages"
  }

  /// Unary call to GetMessages
  ///
  /// - Parameters:
  ///   - request: Request to send to GetMessages.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getMessages(
    _ request: GetMessagesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetMessagesRequest, GetMessagesResponse> {
    return self.makeUnaryCall(
      path: MessagesClientMetadata.Methods.getMessages.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetMessagesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension MessagesClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "MessagesNIOClient")
internal final class MessagesClient: MessagesClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: MessagesClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: MessagesClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the Messages service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: MessagesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct MessagesNIOClient: MessagesClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: MessagesClientInterceptorFactoryProtocol?

  /// Creates a client for the Messages service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: MessagesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol MessagesAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: MessagesClientInterceptorFactoryProtocol? { get }

  func makeGetMessagesCall(
    _ request: GetMessagesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<GetMessagesRequest, GetMessagesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension MessagesAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return MessagesClientMetadata.serviceDescriptor
  }

  internal var interceptors: MessagesClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetMessagesCall(
    _ request: GetMessagesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<GetMessagesRequest, GetMessagesResponse> {
    return self.makeAsyncUnaryCall(
      path: MessagesClientMetadata.Methods.getMessages.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetMessagesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension MessagesAsyncClientProtocol {
  internal func getMessages(
    _ request: GetMessagesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> GetMessagesResponse {
    return try await self.performAsyncUnaryCall(
      path: MessagesClientMetadata.Methods.getMessages.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetMessagesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct MessagesAsyncClient: MessagesAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: MessagesClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: MessagesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol MessagesClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getMessages'.
  func makeGetMessagesInterceptors() -> [ClientInterceptor<GetMessagesRequest, GetMessagesResponse>]
}

internal enum MessagesClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Messages",
    fullName: "Messages",
    methods: [
      MessagesClientMetadata.Methods.getMessages,
    ]
  )

  internal enum Methods {
    internal static let getMessages = GRPCMethodDescriptor(
      name: "GetMessages",
      path: "/Messages/GetMessages",
      type: GRPCCallType.unary
    )
  }
}

